githwxi/ATS-Postiats

libc/SATS/stdlib.sats

Updating strol function declarations so the corresponding macros defined in CATS/stdlib.cats are used.

Specifying strol functions as macros.

---

travis-ci/installpkg.sh

It seems to be lack of `cairo`, `pcre` and `glib` packages to install with Homebrew.
`pkg-config` for `gtk+3` dose not work correctly without `XQuartz`.
For now, I didn't include revert comment out commit for `gtk+3` and `gmp`.

Add lack packages for OSX

---

src/pats_comarg.dats

It’s a small error, but I see it whenever I make a mistake on the command line (which is often).

Fixed spelling error

---

src/pats_trans2_staexp.dats

Hi professor,
While debugging assignment 4, I found this typo in the error information: *the static expresstion*.

Fixed typo "expresstion"

---

nix/build.nix
nix/default.nix
nix/shell.nix
nix/tarball.nix
shell.nix

Adds expressions for use with the nix package manager. `shell.nix` in particular is useful with `nix-shell` to build ATS in-tree.

Nix build expressions

---

src/pats_jsonize_synent2.dats

This includes static float expressions in the JSON export process.

Adding static floats to jsonize

---

appveyor/appveyor.yml

Invoking the cygwin setup to install extra packages breaks the git clone by appending the build folder for some reason. Switched to using apt-cyg to install the extra packages.

Fix appveyor build

---

doc/DISTRIB/README
doc/DISTRIB/make_distrib.sh

This is just to make things a little quicker.
Also, a couple of build issues I noticed. The first is the following (ATS2-Postiats-include has a different version)
```
$ ls -al ATS2-* .tgz                                                                                                                  
-rw-r--r--  1 brandon brandon 11191716 Mar 17 20:13 ATS2-Postiats-0.3.10.tgz                                                                                                        
-rw-r--r--  1 brandon brandon    63812 Mar 17 20:13 ATS2-Postiats-contrib-0.3.10.tgz                                                                                                
-rw-r--r--  1 brandon brandon   378983 Mar 17 20:13 ATS2-Postiats-include-0.3.9.tgz         
```
The next is that in `.gitignore` there …

automating build distribution process further

---

share/SCRIPT/buildRelease.sh

Using this method, ATS-includes still build at version 9, because the bug wasn't fixed until after the version 0.3.10 tag. We could potentially revise the tag to be the current state, since the release hasn't been made yet, I suppose.

adding command-line argument for version specification

---

src/pats_lexing.dats

I suspect this should be “// for $2” instead of “// for $^2”

Suspected typo in comment (to be checked)

---

src/pats_lexing.dats
src/pats_symbol.sats

`symbol_FUN` and `symbol_MINUSLTGT`, are declared in `pats_symbols.sats` but nowhere implemented (not only not in `pats_symbols.dats`).

Removing `symbol_FUN` and `symbol_MINUSLTGT`

---

src/pats_lexing.dats
src/pats_lexing.sats
src/pats_lexing_error.dats

No fix was needed for decimal float, as a consequence of already existing rules. Only hexadecimal float was fixed.

Floats require integral and/or fractional part

---

src/pats_lexing.dats
src/pats_lexing.sats
src/pats_lexing_error.dats

There was a remaining issue with hexadecimal integers as well: the digits sequence cannot be empty neither.
Additionally, `LE_FINTEGRAL_missing` is removed from the previous fix, to keep only `LE_FINTFRAC_missing`, which is simpler and more meaningful to users.

Fix hex int format

---

contrib/CATS-atscc2js/DATS/atscc2js_emit.dats
contrib/CATS-parsemit/SATS/catsparse_emit.sats

This implements flat record selection for `$extype_struct` record types.
Here is an example of usage:
```
typedef domrect = $extype_struct "DOMRect" of {
x= double, y= double
}
extern
fun getrect (): domrect = "mac#"
%{$
function getrect() { return { x : 1.0, y : 2.0 }; }
%}
fun hello () = {
val r = getrect ()
val () = println!(r.x)
val () = println!(r.y)
}
```
I use this feature in [typesafe-dom](https://github.com/ashalkhakov/typesafe-dom/blob/master/test/bcr.dats#L40) to avoid having to write lots of getters. :)

atscc2js: flat record selection

---

contrib/CATS-atscc2php/DATS/atscc2php_emit.dats

Dollar signs inject variables into strings in PHP, and need to be escaped.  Curly brackets ({}) are also used to inject variables in PHP, but they should have no effect if dollar signs are escaped.

atscc2php: Escape dollar signs in string literals.

---

doc/EXAMPLE/ATSLIB/libats_ML_array0.dats
share/SCRIPT/build_release.sh

The variables "CONFIGURE_AC" and "AC_INIT_VERSION" should be placed within the function "check_ac_init_version" so that PATSHOME is properly set. Otherwise, PATSHOME expands to "". 
While testing the potential release archives, ATS2-Postiats-int-0.3.13.tgz and ATS2-Postiats-gmp-0.3.13.tgz with the tests from doc/EXAMPLE/ATSLIB/ , [doc/EXAMPLE/ATSLIB/libats_ML_array0.dats](https://github.com/githwxi/ATS-Postiats/blob/master/doc/EXAMPLE/ATSLIB/libats_ML_array0.dats) fails to compile due to changes in [libats/ML/SATS/array0.sats](https://github.com/githwxi/ATS-Postiats/blame/master/libats/ML/SATS/array0.sats#L201)
The changes to the test file, doc/EXAMPLE/ATSLIB/libats_ML_array0.dats, reflect previous additions, seen here: https://github.com/githwxi/ATS-Postiats/commit/8f360b05caf3a4b0172c9f9 …

Minor change to build script.

---

doc/DISTRIB/README
share/SCRIPT/build_release.sh

I observed that the include tgz generated had different checksums during different builds, but upon extracting, all the files within the archive had the same checksum, so it is probably ok.

updating directions and adding back generation of ATS include tgz

---

contrib/libatscc2js/ATS2-0.3.2/CATS/bool_cats.js
contrib/libatscc2js/ATS2-0.3.2/Makefile
contrib/libatscc2js/CATS/bool_cats.js

This request consists of two changes:
1) Use `patsopt` instead of file concatenation to create `libatscc2js_all.js`:  fixes a namespace collision (previously, `_ats2jspre_list_loop_3` would be declared twice, possibly causing bugs); duplicate names also interfere with JS tooling. 
2) Remove duplicate functions from bool_cats.js: duplicate names interfere with JS tooling.

libatscc2js: fix duplicate function declarations

---

prelude/basics_sta.sats
src/pats_lexing.dats
src/pats_lexing_error.dats

Fix for lexing character escape sequences

---

src/pats_parsing_base.dats

I noticed while trying to use the `~` operator on an effect that it didn't seem to be working. Lookgin at `p_e0fftag`, I noticed that `0` was being passed to `e0fftag_cst` in both the `T_BANG` and `T_TILDE` cases.
You can observe the change in behaviour with the example program:
```ats
fun f .<>. ():<1,~all> void = ()
val (_) = $showtype f
implmnt main0 () = ()
```
If you use a compile before this PR, you see `eff=S2EFFset(1)`:
```
cpm@nyx ~/src/ATS-Postiats : neg-effects % PATSHOME=~/local/lib/ats2-postiats-0.4.0 ~/local/bin/patsopt -tc -d test0.dats
**SHOWTYPE[UP]**(/home/cpm/src/ATS-Postiats/test0.dats: 57(line=5, offs=21) -- 58(line=5, offs=22)): S2Efun(FUN; lin=0; eff=S2EFFset(1); npf=-1; ; S2Ecst(void)): S2RTbas(S2RTBASimp(0; type))
```
After this change, it's `eff=S2EFFset(0)`:
``` …
```

Fix negation in effects list

---

contrib/CATS-atscc2clj/Makefile
contrib/CATS-parsemit/Makefile
utils/libatsopt/Makefile
utils/libatsynmark/Makefile

This fixes some the broken Makefiles that kept `C9-ATS2-install-latest.sh`  from being able to run all the way. https://github.com/ats-lang/ats-lang.github.io/issues/8#issuecomment-1368496645
Will in addition need [to fix the paths in that script.](https://github.com/ats-lang/ats-lang.github.io/pull/9)

fix broken Makefiles
